const regionRules = {
    "BY": "[0-7]",
    "BG": "(A|B|BH|BP|BT|E|EB|EH|K|KH|M|H|OP|P|PA|PB|PK|PP|C|CA|CB|CH|CM|CO|CC|CT|T|TX|Y|X)",
    "CZ": "[ABCEHJKLMPSTUV]",
    "MNE": "(AN|BA|BD|BP|BR|CT|DG|GS|HN|KL|KO|MK|NK|PG|PL||PT|PZ|PV|RO|SN|TV|TZ|UL|ZT|ZB)",
}

export const regexes = {
    "AL": "[A-Z]{2}[0-9]{3}[A-Z]{2}",
    "AND": "[A-Z][0-9]{4}",
    "A": "[A-Z^Q]{1,2}([0-9]{1}[A-Z^Q]{3,5}|[0-9]{2}[A-Z^Q]{2,4}|[0-9]{3}[A-Z^Q]{1,3}|[0-9]{4}[A-Z^Q]{1,2}|[0-9]{5}[A-Z^Q]{1})",
    "BY": "[0-9E][0-9]{3}[A-Z]{2}" + regionRules["BY"],
    "B": "([12][A-Z]{3}[0-9]{3}|[A-Z]{3}[0-9]{3})",
    "BIH": "([AEOJKMT]|[0-9])[0-9]{2}[AEOJKMT][0-9]{3}|[AEOJKMT]{2}[0-9]{6}",
    "BG": regionRules["BG"] + "[0-9]{4}[ABEKMHOPCTYX]{2}",
    "HR": "[A-Z]{2}[0-9]{3,4}[A-Z]{1,2}",
    "CY": "[A-Z]{3}[0-9]{3}",
    "CZ": "[1-9]" + regionRules["CZ"] + "([0-9][A-Z]){2}[0-9]{3}",
    "DK": "[A-Z]{2}[0-9]{5}",
    "EST": "[0-9]{3}[A-Z]{3}",
    "FIN": "[A-Z]{3}[0-9]{3}",
    "F": "[A-Z]{2}[0-9]{3}[A-Z]{2}",
    "D": "[A-Z]{3,5}[0-9]{2,4}",
    "GR": "[A-Z]{3}[0-9]{4}",
    "H": "[A-Z]{4}[0-9]{3}",
    "IS": "[A-Z]{2}[A-Z0-9][0-9]{2}",
    "IRL": "[0-9]{2,3}[A-Z][0-9]{1,6}",
    "I": "[A-Z^QUIO]{2}[0-9]{3}[A-Z^QUIO]{2}",
    "LV": "[A-Z]{2}[0-9]{4}",
    "FL": "FL[0-9]{4,5}",
    "LT": "[A-Z]{3}[0-9]{3}",
    "L": "[A-Z]{2}[0-9]{3,4}",
    "M": "[A-Z]{3}[0-9]{3}",
    "MD": "[A-Z]{3}[0-9]{3}",
    "MC": "[0-9A-Z]{4}",
    "MNE": regionRules["MNE"] + "[A-Z]{2}[0-9]{3}",
    "NL": "(([0-9]{2}[A-Z]{4})|([0-9]{2}[A-Z]{3}[0-9])|([0-9][A-Z]{3}[0-9]{2})|([A-Z]{2}[0-9]{3}[A-Z])|([A-Z][0-9]{3}[A-Z]{2}))",

}

export const country = {
    "AL": "Albania",
    "AND": "Andorra",
    "A": "Austria",
    "BY": "Belarus",
    "B": "Belgium",
    "BIH": "Bosnia and Herzegovina",
    "BG": "Bulgaria",
    "HR": "Croatia",
    "CY": "Cyprus",
    "CZ": "Czech",
    "DK": "Denmark",
    "EST": "Estonia",
    "FIN": "Finland",
    "F": "France",
    "D": "Germany",
    "GR": "Greece",
    "H": "Hungary",
    "IS": "Iceland",
    "IRL": "Ireland",
    "I": "Italy",
    "LV": "Latvia",
    "FL": "Liechtenstein",
    "LT": "Lithuania",
    "L": "Luxembourg",
    "M": "Malta",
    "MD": "Moldova",
    "MC": "Monaco",
    "MNE": "Montenegro",
    "NL": "Netherlands",

}